Add google consent, DEV-406
customgento/module-cookiebot-m2 pull request #26
Opened 2024-02-27 08:06 UTC by iranimij

2024-02-27 10:22 UTC, sprankhub requested changes

2024-02-27 10:22 UTC, sprankhub commented on Model/Config.php
> +    public function googleConsentIsEnabled(): bool
Please rename to `isGoogleConsentModeEnabled` to match the other method names.

2024-02-27 10:22 UTC, sprankhub commented on Model/Config.php
> +    public const XML_PATH_GOOGLE_CONSENT = 'web/cookiebot/google_consent';
Let's rename this setting to `use_google_consent_mode`. The constant name should be names accordigly.

2024-02-27 10:22 UTC, sprankhub commented on view/frontend/templates/script.phtml
> +if ($viewModel->googleConsentIsEnabled()):
Please extend the tests to cover this new script.

2024-02-28 16:14 UTC, sprankhub approved these changes

2024-02-28 16:14 UTC, merged

2024-03-04 07:47 UTC, Andrii-Antoniuk commented
Thank you for your work! ❤️